export const VALID_RANGES = [
  [67072, 67382], // U+10600 to U+106AE (Linear A)
  [67392, 67413], // U+106B0 to U+106CD (Linear A)
  [67424, 67431], // U+106D8 to U+106DF (Linear A)
];
export const SPECIAL_CHARACTER_COUNT = 4;
export const CHARACTER_START_UNLOCK_PERCENT = 0.01;
export const MIN_ROUND_DURATION = 2;
export const INITIAL_ROUND_DURATION = 10;
export const ROUND_ENDING_TIME = MIN_ROUND_DURATION;
export const END_ROUND_DURATION_S = 1;
export const GRID_DEFAULT_ROWS = 1;
export const GRID_DEFAULT_COLS = 1;
export const MAX_SCORE_FOR_SQUARE_GRID = 100;
export const GRID_MAX_ROWS = 10;
export const GRID_MAX_COLS = 20;
export const FADE_IN_DURATION = 2000;
export const FADE_OUT_DURATION = 1000;
export const ROUND_END_EARLY_THRESHOLD = 2000;
export const DEBOUNCE_TIME = 150;

export const DEFAULT_DURATIONS = {
  MIN_ROUND_DURATION,
  INITIAL_ROUND_DURATION,
  TIMER_SWIPE_TRANSITION_DURATION_S: MIN_ROUND_DURATION,
  ROUND_ENDING_TIME,
  END_ROUND_DURATION_S,
  FADE_IN_DURATION,
  FADE_OUT_DURATION,
  ROUND_END_EARLY_THRESHOLD,
};
